server:
  port: 8082
  servlet:
    session:
      timeout: 60
spring:
  session:
    store-type: redis
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
    database: 0
    password:
